version: '3.8'
services:
  webapp:
    restart: always
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    command: npm run serve
    volumes:
      - .:/app
      - /app/node_modules
      